/* eslint-disable no-useless-escape */
export const embedsOverviewResponse = {
  id: 25,
  title: 'Embeds overview',
  shortDescription:
    'While most embeds could be handles just by putting them into WebView, I suggest making each separate component and using WebView only as a fallback. Most or even every embed uses the same core\/embed block and just swaps out attr&#8217;s providerNameSlug to a different domain. Thats why i&#8217;ll only showcase some of the more popular [&hellip;]',
  previewImage: false,
  date: '2026-09-14 19:29:41',
  author: {
    nickname: null,
    name: ' ',
    description: null,
    avatarUrl:
      'https:\/\/secure.gravatar.com\/avatar\/8368b6b19c1f0ef13e2e416945f18182054a70e82f74bc1a2ea160021c70f8aa?s=96&d=mm&r=g',
  },
  blocks: [
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>While most embeds could be handles just by putting them into WebView, I suggest making each separate component and using WebView only as a fallback.<br><\/p>\n',
      innerContent: [
        '\n<p>While most embeds could be handles just by putting them into WebView, I suggest making each separate component and using WebView only as a fallback.<br><\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        "\n<p>Most or even every embed uses the same core\/embed block and just swaps out attr's providerNameSlug to a different domain. Thats why i'll only showcase some of the more popular choices here.<\/p>\n",
      innerContent: [
        "\n<p>Most or even every embed uses the same core\/embed block and just swaps out attr's providerNameSlug to a different domain. Thats why i'll only showcase some of the more popular choices here.<\/p>\n",
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Base Embed (should auto convert to Twitter\/X):<\/p>\n',
      innerContent: [
        '\n<p>Base Embed (should auto convert to Twitter\/X):<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/twitter.com\/ParksCanada\/status\/2016603067764854904',
        type: 'rich',
        providerNameSlug: 'x',
        responsive: true,
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-rich is-provider-x wp-block-embed-x"><div class="wp-block-embed__wrapper">\nhttps:\/\/twitter.com\/ParksCanada\/status\/2016603067764854904\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-rich is-provider-x wp-block-embed-x"><div class="wp-block-embed__wrapper">\nhttps:\/\/twitter.com\/ParksCanada\/status\/2016603067764854904\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Twitter\/X Embed:<\/p>\n',
      innerContent: ['\n<p>Twitter\/X Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/twitter.com\/OntarioNature\/status\/2095933603838333426',
        type: 'rich',
        providerNameSlug: 'x',
        responsive: true,
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-rich is-provider-x wp-block-embed-x"><div class="wp-block-embed__wrapper">\nhttps:\/\/twitter.com\/OntarioNature\/status\/2095933603838333426\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-rich is-provider-x wp-block-embed-x"><div class="wp-block-embed__wrapper">\nhttps:\/\/twitter.com\/OntarioNature\/status\/2095933603838333426\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>YouTube Embed:<\/p>\n',
      innerContent: ['\n<p>YouTube Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/www.youtube.com\/watch?v=Dr4lseoF82c',
        type: 'video',
        providerNameSlug: 'youtube',
        responsive: true,
        className: 'wp-embed-aspect-16-9 wp-has-aspect-ratio',
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.youtube.com\/watch?v=Dr4lseoF82c\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.youtube.com\/watch?v=Dr4lseoF82c\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>WordPress Embed:<\/p>\n',
      innerContent: ['\n<p>WordPress Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/wordpress.com\/blog\/2026\/06\/24\/jetpack-search-7-0-woocommerce\/',
        type: 'wp-embed',
        providerNameSlug: 'wordpress-com-blog',
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-wp-embed is-provider-wordpress-com-blog wp-block-embed-wordpress-com-blog"><div class="wp-block-embed__wrapper">\nhttps:\/\/wordpress.com\/blog\/2026\/06\/24\/jetpack-search-7-0-woocommerce\/\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-wp-embed is-provider-wordpress-com-blog wp-block-embed-wordpress-com-blog"><div class="wp-block-embed__wrapper">\nhttps:\/\/wordpress.com\/blog\/2026\/06\/24\/jetpack-search-7-0-woocommerce\/\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>SoundCloud Embed:<\/p>\n',
      innerContent: ['\n<p>SoundCloud Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/soundcloud.com\/hypernoiz\/letmedown',
        type: 'rich',
        providerNameSlug: 'soundcloud',
        responsive: true,
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-rich is-provider-soundcloud wp-block-embed-soundcloud"><div class="wp-block-embed__wrapper">\nhttps:\/\/soundcloud.com\/hypernoiz\/letmedown\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-rich is-provider-soundcloud wp-block-embed-soundcloud"><div class="wp-block-embed__wrapper">\nhttps:\/\/soundcloud.com\/hypernoiz\/letmedown\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Spotify Embed:<\/p>\n',
      innerContent: ['\n<p>Spotify Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/open.spotify.com\/album\/5deIuq5moCfyQ2hnpnb3n8',
        type: 'rich',
        providerNameSlug: 'spotify',
        responsive: true,
        className: 'wp-embed-aspect-21-9 wp-has-aspect-ratio',
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-rich is-provider-spotify wp-block-embed-spotify wp-embed-aspect-21-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/open.spotify.com\/album\/5deIuq5moCfyQ2hnpnb3n8\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-rich is-provider-spotify wp-block-embed-spotify wp-embed-aspect-21-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/open.spotify.com\/album\/5deIuq5moCfyQ2hnpnb3n8\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Vimeo Embed:<\/p>\n',
      innerContent: ['\n<p>Vimeo Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/www.europeanfilmawards.eu\/vimeo-movie\/creation\/',
        type: 'wp-embed',
        providerNameSlug: 'european-film-academy',
        responsive: true,
        className: 'wp-embed-aspect-16-9 wp-has-aspect-ratio',
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-wp-embed is-provider-european-film-academy wp-block-embed-european-film-academy wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.europeanfilmawards.eu\/vimeo-movie\/creation\/\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-wp-embed is-provider-european-film-academy wp-block-embed-european-film-academy wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.europeanfilmawards.eu\/vimeo-movie\/creation\/\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Dailymotion Embed:<\/p>\n',
      innerContent: ['\n<p>Dailymotion Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/www.dailymotion.com\/video\/xamjdsy',
        type: 'video',
        providerNameSlug: 'dailymotion',
        responsive: true,
        className: 'wp-embed-aspect-16-9 wp-has-aspect-ratio',
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-video is-provider-dailymotion wp-block-embed-dailymotion wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.dailymotion.com\/video\/xamjdsy\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-video is-provider-dailymotion wp-block-embed-dailymotion wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.dailymotion.com\/video\/xamjdsy\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Reddit Embed:<\/p>\n',
      innerContent: ['\n<p>Reddit Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/www.reddit.com\/r\/UFOs\/comments\/1uqapl5\/pilot_records_ufos_over_ceara_in_brazil\/',
        type: 'rich',
        providerNameSlug: 'reddit',
        responsive: true,
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-rich is-provider-reddit wp-block-embed-reddit"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.reddit.com\/r\/UFOs\/comments\/1uqapl5\/pilot_records_ufos_over_ceara_in_brazil\/\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-rich is-provider-reddit wp-block-embed-reddit"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.reddit.com\/r\/UFOs\/comments\/1uqapl5\/pilot_records_ufos_over_ceara_in_brazil\/\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>TikTok Embed:<\/p>\n',
      innerContent: ['\n<p>TikTok Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/www.tiktok.com\/@_rl9\/video\/7632240883416468769',
        type: 'video',
        providerNameSlug: 'tiktok',
        responsive: true,
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-video is-provider-tiktok wp-block-embed-tiktok"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.tiktok.com\/@_rl9\/video\/7632240883416468769\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-video is-provider-tiktok wp-block-embed-tiktok"><div class="wp-block-embed__wrapper">\nhttps:\/\/www.tiktok.com\/@_rl9\/video\/7632240883416468769\n<\/div><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Bluesky Embed:<\/p>\n',
      innerContent: ['\n<p>Bluesky Embed:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/embed',
      attrs: {
        url: 'https:\/\/bsky.app\/profile\/godlessmom.bsky.social\/post\/3mq4ac75f4t2x',
        type: 'rich',
        providerNameSlug: 'bluesky',
      },
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-embed is-type-rich is-provider-bluesky wp-block-embed-bluesky"><div class="wp-block-embed__wrapper">\nhttps:\/\/bsky.app\/profile\/godlessmom.bsky.social\/post\/3mq4ac75f4t2x\n<\/div><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-embed is-type-rich is-provider-bluesky wp-block-embed-bluesky"><div class="wp-block-embed__wrapper">\nhttps:\/\/bsky.app\/profile\/godlessmom.bsky.social\/post\/3mq4ac75f4t2x\n<\/div><\/figure>\n',
      ],
    },
  ],
};
