/* eslint-disable no-useless-escape */
export const textOverviewResponse = {
  id: 8,
  title: 'Text overview',
  shortDescription:
    'This is a standard paragraph. Paragraph like these are going to be used to describe what content is being presented to make sure it&#8217;s correct. Headings (h1 &gt; h6): Heading 1 Heading 2 Heading 3 Heading 4 Heading 5 Heading 6 Lists: undordered ordered (numbered) ordered (numbered) with offset ordered (upper-alpha) ordered (lower-roman) Quote: This [&hellip;]',
  previewImage: false,
  date: '2026-09-14 17:45:39',
  author: {
    nickname: null,
    name: ' ',
    description: null,
    avatarUrl:
      'https:\/\/secure.gravatar.com\/avatar\/8368b6b19c1f0ef13e2e416945f18182054a70e82f74bc1a2ea160021c70f8aa?s=96&d=mm&r=g',
  },
  blocks: [
    {
      blockName: 'core\/paragraph',
      attrs: { className: 'is-style-default' },
      innerBlocks: [],
      innerHTML:
        '\n<p class="is-style-default">This is a standard paragraph.<\/p>\n',
      innerContent: [
        '\n<p class="is-style-default">This is a standard paragraph.<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        "\n<p>Paragraph like these are going to be used to describe what content is being presented to make sure it's correct.<br><\/p>\n",
      innerContent: [
        "\n<p>Paragraph like these are going to be used to describe what content is being presented to make sure it's correct.<br><\/p>\n",
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Headings (h1 &gt; h6):<\/p>\n',
      innerContent: ['\n<p>Headings (h1 &gt; h6):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/heading',
      attrs: { level: 1 },
      innerBlocks: [],
      innerHTML: '\n<h1 class="wp-block-heading">Heading 1<\/h1>\n',
      innerContent: ['\n<h1 class="wp-block-heading">Heading 1<\/h1>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/heading',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<h2 class="wp-block-heading">Heading 2<\/h2>\n',
      innerContent: ['\n<h2 class="wp-block-heading">Heading 2<\/h2>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/heading',
      attrs: { level: 3 },
      innerBlocks: [],
      innerHTML: '\n<h3 class="wp-block-heading">Heading 3<\/h3>\n',
      innerContent: ['\n<h3 class="wp-block-heading">Heading 3<\/h3>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/heading',
      attrs: { level: 4 },
      innerBlocks: [],
      innerHTML: '\n<h4 class="wp-block-heading">Heading 4<\/h4>\n',
      innerContent: ['\n<h4 class="wp-block-heading">Heading 4<\/h4>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/heading',
      attrs: { level: 5 },
      innerBlocks: [],
      innerHTML: '\n<h5 class="wp-block-heading">Heading 5<\/h5>\n',
      innerContent: ['\n<h5 class="wp-block-heading">Heading 5<\/h5>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/heading',
      attrs: { level: 6 },
      innerBlocks: [],
      innerHTML: '\n<h6 class="wp-block-heading">Heading 6<\/h6>\n',
      innerContent: ['\n<h6 class="wp-block-heading">Heading 6<\/h6>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Lists:<\/p>\n',
      innerContent: ['\n<p>Lists:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>undordered<br><\/p>\n',
      innerContent: ['\n<p>undordered<br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/list',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>this is and example<\/li>\n',
          innerContent: ['\n<li>this is and example<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>of unordered list<\/li>\n',
          innerContent: ['\n<li>of unordered list<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>with a few elements<\/li>\n',
          innerContent: ['\n<li>with a few elements<\/li>\n'],
        },
      ],
      innerHTML: '\n<ul class="wp-block-list">\n\n\n\n<\/ul>\n',
      innerContent: [
        '\n<ul class="wp-block-list">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/ul>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br>ordered (numbered)<\/p>\n',
      innerContent: ['\n<p><br>ordered (numbered)<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/list',
      attrs: { ordered: true },
      innerBlocks: [
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>and now<\/li>\n',
          innerContent: ['\n<li>and now<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>the same thing<\/li>\n',
          innerContent: ['\n<li>the same thing<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>with ordered list<\/li>\n',
          innerContent: ['\n<li>with ordered list<\/li>\n'],
        },
      ],
      innerHTML: '\n<ol class="wp-block-list">\n\n\n\n<\/ol>\n',
      innerContent: [
        '\n<ol class="wp-block-list">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/ol>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br>ordered (numbered) with offset<\/p>\n',
      innerContent: ['\n<p><br>ordered (numbered) with offset<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/list',
      attrs: { ordered: true, start: 7 },
      innerBlocks: [
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<li>this ordered list should start from number 7<\/li>\n',
          innerContent: [
            '\n<li>this ordered list should start from number 7<\/li>\n',
          ],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>and go up<\/li>\n',
          innerContent: ['\n<li>and go up<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>to number 9<\/li>\n',
          innerContent: ['\n<li>to number 9<\/li>\n'],
        },
      ],
      innerHTML: '\n<ol start="7" class="wp-block-list">\n\n\n\n<\/ol>\n',
      innerContent: [
        '\n<ol start="7" class="wp-block-list">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/ol>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br>ordered (upper-alpha)<\/p>\n',
      innerContent: ['\n<p><br>ordered (upper-alpha)<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/list',
      attrs: { ordered: true, type: 'upper-alpha' },
      innerBlocks: [
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>this list will have <\/li>\n',
          innerContent: ['\n<li>this list will have <\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>letters as a points<\/li>\n',
          innerContent: ['\n<li>letters as a points<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: "\n<li>isn't that cool?<\/li>\n",
          innerContent: ["\n<li>isn't that cool?<\/li>\n"],
        },
      ],
      innerHTML:
        '\n<ol style="list-style-type:upper-alpha" class="wp-block-list">\n\n\n\n<\/ol>\n',
      innerContent: [
        '\n<ol style="list-style-type:upper-alpha" class="wp-block-list">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/ol>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br>ordered (lower-roman)<\/p>\n',
      innerContent: ['\n<p><br>ordered (lower-roman)<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/list',
      attrs: { ordered: true, type: 'lower-roman' },
      innerBlocks: [
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>it also supports lowercase roman numerals<\/li>\n',
          innerContent: [
            '\n<li>it also supports lowercase roman numerals<\/li>\n',
          ],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>thats pretty neat too<\/li>\n',
          innerContent: ['\n<li>thats pretty neat too<\/li>\n'],
        },
        {
          blockName: 'core\/list-item',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<li>aint it?<\/li>\n',
          innerContent: ['\n<li>aint it?<\/li>\n'],
        },
      ],
      innerHTML:
        '\n<ol style="list-style-type:lower-roman" class="wp-block-list">\n\n\n\n<\/ol>\n',
      innerContent: [
        '\n<ol style="list-style-type:lower-roman" class="wp-block-list">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/ol>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Quote:<\/p>\n',
      innerContent: ['\n<p>Quote:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/quote',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>This is an example quote<\/p>\n',
          innerContent: ['\n<p>This is an example quote<\/p>\n'],
        },
      ],
      innerHTML: '\n<blockquote class="wp-block-quote"><\/blockquote>\n',
      innerContent: [
        '\n<blockquote class="wp-block-quote">',
        null,
        '<\/blockquote>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Code:<\/p>\n',
      innerContent: ['\n<p>Code:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/code',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<pre class="wp-block-code"><code>\/\/Example code fragment\nconst foo = "bar";<\/code><\/pre>\n',
      innerContent: [
        '\n<pre class="wp-block-code"><code>\/\/Example code fragment\nconst foo = "bar";<\/code><\/pre>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Details:<\/p>\n',
      innerContent: ['\n<p>Details:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/details',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/paragraph',
          attrs: { placeholder: 'Type \/ to add a hidden block' },
          innerBlocks: [],
          innerHTML:
            '\n<p>a hidden block contents, that shouldnt  be visible when its collapsed<\/p>\n',
          innerContent: [
            '\n<p>a hidden block contents, that shouldnt  be visible when its collapsed<\/p>\n',
          ],
        },
      ],
      innerHTML:
        '\n<details class="wp-block-details"><summary>summary for a hidden block<\/summary><\/details>\n',
      innerContent: [
        '\n<details class="wp-block-details"><summary>summary for a hidden block<\/summary>',
        null,
        '<\/details>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Math: (would require component capable of LaTeX)<\/p>\n',
      innerContent: [
        '\n<p>Math: (would require component capable of LaTeX)<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/math',
      attrs: { latex: 'x^7 - sqrt(2) + C' },
      innerBlocks: [],
      innerHTML:
        '\n<div class="wp-block-math"><math display="block"><semantics><mrow><msup><mi>x<\/mi><mn>7<\/mn><\/msup><mo>\u2212<\/mo><mi>s<\/mi><mi>q<\/mi><mi>r<\/mi><mi>t<\/mi><mo form="prefix" stretchy="false">(<\/mo><mn>2<\/mn><mo form="postfix" stretchy="false">)<\/mo><mo>+<\/mo><mi>C<\/mi><\/mrow><annotation encoding="application\/x-tex">x^7 - sqrt(2) + C<\/annotation><\/semantics><\/math><\/div>\n',
      innerContent: [
        '\n<div class="wp-block-math"><math display="block"><semantics><mrow><msup><mi>x<\/mi><mn>7<\/mn><\/msup><mo>\u2212<\/mo><mi>s<\/mi><mi>q<\/mi><mi>r<\/mi><mi>t<\/mi><mo form="prefix" stretchy="false">(<\/mo><mn>2<\/mn><mo form="postfix" stretchy="false">)<\/mo><mo>+<\/mo><mi>C<\/mi><\/mrow><annotation encoding="application\/x-tex">x^7 - sqrt(2) + C<\/annotation><\/semantics><\/math><\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Preformatted:<\/p>\n',
      innerContent: ['\n<p>Preformatted:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/preformatted',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<pre class="wp-block-preformatted">this is an example of preformatted text<br>it should show multiple spaces between words below<br><br>should    it   respect    the   spaces   like here<br><\/pre>\n',
      innerContent: [
        '\n<pre class="wp-block-preformatted">this is an example of preformatted text<br>it should show multiple spaces between words below<br><br>should    it   respect    the   spaces   like here<br><\/pre>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Pullquote:<\/p>\n',
      innerContent: ['\n<p>Pullquote:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/pullquote',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-pullquote"><blockquote><p>This is some quote<\/p><cite>some author<\/cite><\/blockquote><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-pullquote"><blockquote><p>This is some quote<\/p><cite>some author<\/cite><\/blockquote><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>Table (4 columns, 5 rows, with header and footer):<\/p>\n',
      innerContent: [
        '\n<p>Table (4 columns, 5 rows, with header and footer):<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/table',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<figure class="wp-block-table"><table class="has-fixed-layout"><thead><tr><th>Header label<\/th><th>another one<\/th><th><\/th><th>we skipped one huh?<\/th><\/tr><\/thead><tbody><tr><td>this is a 4x3 table<\/td><td>with a text<\/td><td>in every column<\/td><td>at least in the first row<\/td><\/tr><tr><td>second row may only have anything ever in the first column tho<\/td><td><\/td><td><\/td><td><\/td><\/tr><tr><td>and then<\/td><td>the third one<\/td><td><\/td><td><\/td><\/tr><\/tbody><tfoot><tr><td>Footer label<\/td><td><\/td><td>Footer label<\/td><td>Footer label<\/td><\/tr><\/tfoot><\/table><\/figure>\n',
      innerContent: [
        '\n<figure class="wp-block-table"><table class="has-fixed-layout"><thead><tr><th>Header label<\/th><th>another one<\/th><th><\/th><th>we skipped one huh?<\/th><\/tr><\/thead><tbody><tr><td>this is a 4x3 table<\/td><td>with a text<\/td><td>in every column<\/td><td>at least in the first row<\/td><\/tr><tr><td>second row may only have anything ever in the first column tho<\/td><td><\/td><td><\/td><td><\/td><\/tr><tr><td>and then<\/td><td>the third one<\/td><td><\/td><td><\/td><\/tr><\/tbody><tfoot><tr><td>Footer label<\/td><td><\/td><td>Footer label<\/td><td>Footer label<\/td><\/tr><\/tfoot><\/table><\/figure>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Poetry:<\/p>\n',
      innerContent: ['\n<p>Poetry:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/verse',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<pre class="wp-block-verse">I guess<br>this is similar<br>to the preformatted?       altough does it preserve spacing?<br>we\'ll see<\/pre>\n',
      innerContent: [
        '\n<pre class="wp-block-verse">I guess<br>this is similar<br>to the preformatted?       altough does it preserve spacing?<br>we\'ll see<\/pre>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Classic editor:<\/p>\n',
      innerContent: ['\n<p>Classic editor:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML:
        "\n\n<h2>Classic editor is pretty weird.<\/p>\n<\/h2>\n<p>it can have it's own editor within wordpress editor<\/p>\n<p>and is too simple-complicated to fully represent in a general overview of the Text Blocks<\/p>\n\n",
      innerContent: [
        "\n\n<h2>Classic editor is pretty weird.<\/p>\n<\/h2>\n<p>it can have it's own editor within wordpress editor<\/p>\n<p>and is too simple-complicated to fully represent in a general overview of the Text Blocks<\/p>\n\n",
      ],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>This is a longer paragraph that will contain some inline styling like: <strong>bold<\/strong>, <em>italic<\/em>, <s>strike<\/s>, super<sup>script<\/sup>, sub<sub>script<\/sub>, green <mark style="background-color:rgba(0, 0, 0, 0);color:#19c21f" class="has-inline-color">high<\/mark><mark style="background-color:rgba(0, 0, 0, 0);color:#6d946e" class="has-inline-color">light<\/mark>, a fragment of <code>inline code<\/code>, and a <a href="https:\/\/google.com">google<\/a> link<\/p>\n',
      innerContent: [
        '\n<p>This is a longer paragraph that will contain some inline styling like: <strong>bold<\/strong>, <em>italic<\/em>, <s>strike<\/s>, super<sup>script<\/sup>, sub<sub>script<\/sub>, green <mark style="background-color:rgba(0, 0, 0, 0);color:#19c21f" class="has-inline-color">high<\/mark><mark style="background-color:rgba(0, 0, 0, 0);color:#6d946e" class="has-inline-color">light<\/mark>, a fragment of <code>inline code<\/code>, and a <a href="https:\/\/google.com">google<\/a> link<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>this should sum up the most basic examples of Text content on Wordpress.<\/p>\n',
      innerContent: [
        '\n<p>this should sum up the most basic examples of Text content on Wordpress.<\/p>\n',
      ],
    },
  ],
};
