/* eslint-disable no-useless-escape */
export const widgetsOverviewResponse = {
  id: 21,
  title: 'Widgets overview',
  shortDescription:
    'Lets check widgets blocks: Archives: Calendar: Terms List: Terms List (dropdown): Categories List: Categories List (dropdown): Custom HTML: a simple paragraph in custom html a an image below: and an iframe: Latest Comments: Latest Posts: Page List: RSS: Search: Shortcode: Social Icons (amazon, bandcamp, bluesky, etsy + empty wordpress): Tag Cloud:',
  previewImage: false,
  date: '2026-09-14 19:22:40',
  author: {
    nickname: null,
    name: ' ',
    description: null,
    avatarUrl:
      'https:\/\/secure.gravatar.com\/avatar\/8368b6b19c1f0ef13e2e416945f18182054a70e82f74bc1a2ea160021c70f8aa?s=96&d=mm&r=g',
  },
  blocks: [
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Lets check widgets blocks:<\/p>\n',
      innerContent: ['\n<p>Lets check widgets blocks:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Archives:<\/p>\n',
      innerContent: ['\n<p>Archives:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/archives',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Calendar:<\/p>\n',
      innerContent: ['\n<p>Calendar:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/calendar',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Terms List:<\/p>\n',
      innerContent: ['\n<p>Terms List:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/categories',
      attrs: { taxonomy: 'post_tag', showPostCounts: true, showEmpty: true },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Terms List (dropdown):<\/p>\n',
      innerContent: ['\n<p>Terms List (dropdown):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/categories',
      attrs: {
        taxonomy: 'post_tag',
        displayAsDropdown: true,
        showPostCounts: true,
        showEmpty: true,
      },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Categories List:<\/p>\n',
      innerContent: ['\n<p>Categories List:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/categories',
      attrs: { showHierarchy: true, showPostCounts: true, showEmpty: true },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Categories List (dropdown):<\/p>\n',
      innerContent: ['\n<p>Categories List (dropdown):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/categories',
      attrs: {
        displayAsDropdown: true,
        showHierarchy: true,
        showPostCounts: true,
        showEmpty: true,
      },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Custom HTML:<\/p>\n',
      innerContent: ['\n<p>Custom HTML:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/html',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>a simple paragraph in custom html<\/p>\n<p>a an image below: <\/p>\n<img src="https:\/\/placehold.net\/400x400.png">\n<br>\n<p>and an iframe: <\/p>\n<iframe src="https:\/\/www.facebook.com\/plugins\/post.php?href=https%3A%2F%2Fwww.facebook.com%2FParksCanada%2Fposts%2Fpfbid02H6bhzvREuLC8cxgnUHbg4jNKy9oWrPuiMrUqfnqfk3nBU8qSKrQFi4Anb5pVtB7wl&show_text=true&width=500" width="500" height="793" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"><\/iframe>\n',
      innerContent: [
        '\n<p>a simple paragraph in custom html<\/p>\n<p>a an image below: <\/p>\n<img src="https:\/\/placehold.net\/400x400.png">\n<br>\n<p>and an iframe: <\/p>\n<iframe src="https:\/\/www.facebook.com\/plugins\/post.php?href=https%3A%2F%2Fwww.facebook.com%2FParksCanada%2Fposts%2Fpfbid02H6bhzvREuLC8cxgnUHbg4jNKy9oWrPuiMrUqfnqfk3nBU8qSKrQFi4Anb5pVtB7wl&show_text=true&width=500" width="500" height="793" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"><\/iframe>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Latest Comments:<\/p>\n',
      innerContent: ['\n<p>Latest Comments:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/latest-comments',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Latest Posts:<\/p>\n',
      innerContent: ['\n<p>Latest Posts:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/latest-posts',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Page List:<\/p>\n',
      innerContent: ['\n<p>Page List:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/page-list',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>RSS:<\/p>\n',
      innerContent: ['\n<p>RSS:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/rss',
      attrs: { feedURL: 'https:\/\/wordpress.org\/news\/' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Search:<\/p>\n',
      innerContent: ['\n<p>Search:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/search',
      attrs: { label: 'Search', buttonText: 'Search' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Shortcode:<\/p>\n',
      innerContent: ['\n<p>Shortcode:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/shortcode',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>Social Icons (amazon, bandcamp, bluesky, etsy + empty wordpress):<\/p>\n',
      innerContent: [
        '\n<p>Social Icons (amazon, bandcamp, bluesky, etsy + empty wordpress):<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/social-links',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/social-link',
          attrs: { url: 'https:\/\/amazon.com', service: 'amazon' },
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
        {
          blockName: 'core\/social-link',
          attrs: { url: 'https:\/\/bandcamp.com', service: 'bandcamp' },
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
        {
          blockName: 'core\/social-link',
          attrs: { url: 'https:\/\/bsky.app', service: 'bluesky' },
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
        {
          blockName: 'core\/social-link',
          attrs: { url: 'https:\/\/etsy.com', service: 'etsy' },
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
        {
          blockName: 'core\/social-link',
          attrs: { service: 'wordpress' },
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
      ],
      innerHTML: '\n<ul class="wp-block-social-links">\n\n\n\n\n\n\n\n<\/ul>\n',
      innerContent: [
        '\n<ul class="wp-block-social-links">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/ul>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Tag Cloud:<\/p>\n',
      innerContent: ['\n<p>Tag Cloud:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/tag-cloud',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><\/p>\n',
      innerContent: ['\n<p><\/p>\n'],
    },
  ],
};
