/* eslint-disable no-useless-escape */
export const themeOverviewResponse = {
  id: 23,
  title: 'Theme overview',
  shortDescription:
    'Let&#8217;s see what theme blocks have to offer. Navigation: Site Logo: Site Title: Site Tagline: Query Loop (just one example of many): Avatar: Title: Excerpt: Featured Image: Author Name: Comments Count: Comments Link: Date: Post Date: Modified Date: Categories: Tags: Previous Post: Next Post: Time to Read: Word Count: Read More (default text): Read More [&hellip;]',
  previewImage: false,
  date: '2026-09-14 19:23:51',
  author: {
    nickname: null,
    name: ' ',
    description: null,
    avatarUrl:
      'https:\/\/secure.gravatar.com\/avatar\/8368b6b19c1f0ef13e2e416945f18182054a70e82f74bc1a2ea160021c70f8aa?s=96&d=mm&r=g',
  },
  blocks: [
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: "\n<p>Let's see what theme blocks have to offer.<\/p>\n",
      innerContent: ["\n<p>Let's see what theme blocks have to offer.<\/p>\n"],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Navigation:<\/p>\n',
      innerContent: ['\n<p>Navigation:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/navigation',
      attrs: { ref: 4 },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Site Logo:<\/p>\n',
      innerContent: ['\n<p>Site Logo:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/site-logo',
      attrs: { shouldSyncIcon: true },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Site Title:<\/p>\n',
      innerContent: ['\n<p>Site Title:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/site-title',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Site Tagline:<\/p>\n',
      innerContent: ['\n<p>Site Tagline:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/site-tagline',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Query Loop (just one example of many):<\/p>\n',
      innerContent: ['\n<p>Query Loop (just one example of many):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/query',
      attrs: {
        queryId: 31,
        query: {
          perPage: 10,
          pages: 0,
          offset: 0,
          postType: 'post',
          order: 'desc',
          orderBy: 'date',
          author: '',
          search: '',
          exclude: [],
          sticky: '',
          inherit: true,
          excludeCurrent: null,
        },
        metadata: {
          categories: ['posts'],
          patternName: 'core\/fullwidth-posts-with-uppercase-titles',
          name: 'Fullwidth posts with uppercase titles',
        },
        align: 'full',
        layout: { type: 'default' },
      },
      innerBlocks: [
        {
          blockName: 'core\/group',
          attrs: {
            align: 'full',
            style: {
              spacing: {
                padding: { top: '0', right: '0', bottom: '0', left: '0' },
              },
            },
            layout: { type: 'default' },
          },
          innerBlocks: [
            {
              blockName: 'core\/post-template',
              attrs: { style: { typography: { textTransform: 'none' } } },
              innerBlocks: [
                {
                  blockName: 'core\/group',
                  attrs: {
                    style: {
                      border: {
                        bottom: {
                          color: 'var:preset|color|contrast',
                          width: '1px',
                        },
                      },
                    },
                    layout: { type: 'default' },
                  },
                  innerBlocks: [
                    {
                      blockName: 'core\/group',
                      attrs: {
                        style: {
                          spacing: {
                            padding: {
                              top: '16px',
                              right: '16px',
                              bottom: '16px',
                              left: '16px',
                            },
                          },
                        },
                        layout: {
                          type: 'flex',
                          flexWrap: 'nowrap',
                          justifyContent: 'space-between',
                        },
                      },
                      innerBlocks: [
                        {
                          blockName: 'core\/group',
                          attrs: {
                            style: { spacing: { blockGap: '4px' } },
                            layout: { type: 'flex', flexWrap: 'nowrap' },
                          },
                          innerBlocks: [
                            {
                              blockName: 'core\/paragraph',
                              attrs: [],
                              innerBlocks: [],
                              innerHTML: '\n<p>\u2734\ufe0e<\/p>\n',
                              innerContent: ['\n<p>\u2734\ufe0e<\/p>\n'],
                            },
                            {
                              blockName: 'core\/post-date',
                              attrs: {
                                format: 'M j, Y',
                                metadata: {
                                  bindings: {
                                    datetime: {
                                      source: 'core\/post-data',
                                      args: { field: 'date' },
                                    },
                                  },
                                },
                                style: {
                                  spacing: {
                                    margin: {
                                      top: '0',
                                      right: '0',
                                      bottom: '0',
                                      left: '0',
                                    },
                                  },
                                  elements: {
                                    link: {
                                      color: {
                                        text: 'var:preset|color|contrast',
                                      },
                                    },
                                  },
                                  typography: {
                                    textTransform: 'uppercase',
                                    textAlign: 'left',
                                  },
                                },
                                textColor: 'contrast',
                                fontSize: 'small',
                              },
                              innerBlocks: [],
                              innerHTML: '',
                              innerContent: [],
                            },
                          ],
                          innerHTML:
                            '\n<div class="wp-block-group">\n\n<\/div>\n',
                          innerContent: [
                            '\n<div class="wp-block-group">',
                            null,
                            '\n\n',
                            null,
                            '<\/div>\n',
                          ],
                        },
                        {
                          blockName: 'core\/post-terms',
                          attrs: {
                            term: 'category',
                            prefix: '\u2734\ufe0e ',
                            style: {
                              elements: {
                                link: {
                                  color: { text: 'var:preset|color|contrast' },
                                },
                              },
                              typography: { textTransform: 'uppercase' },
                            },
                            textColor: 'contrast',
                          },
                          innerBlocks: [],
                          innerHTML: '',
                          innerContent: [],
                        },
                      ],
                      innerHTML:
                        '\n<div class="wp-block-group" style="padding-top:16px;padding-right:16px;padding-bottom:16px;padding-left:16px">\n\n<\/div>\n',
                      innerContent: [
                        '\n<div class="wp-block-group" style="padding-top:16px;padding-right:16px;padding-bottom:16px;padding-left:16px">',
                        null,
                        '\n\n',
                        null,
                        '<\/div>\n',
                      ],
                    },
                  ],
                  innerHTML:
                    '\n<div class="wp-block-group" style="border-bottom-color:var(--wp--preset--color--contrast);border-bottom-width:1px"><\/div>\n',
                  innerContent: [
                    '\n<div class="wp-block-group" style="border-bottom-color:var(--wp--preset--color--contrast);border-bottom-width:1px">',
                    null,
                    '<\/div>\n',
                  ],
                },
                {
                  blockName: 'core\/group',
                  attrs: {
                    style: {
                      spacing: {
                        padding: {
                          top: '16px',
                          bottom: 'var:preset|spacing|70',
                          right: '16px',
                          left: '16px',
                        },
                      },
                    },
                    layout: { type: 'flex', orientation: 'vertical' },
                  },
                  innerBlocks: [
                    {
                      blockName: 'core\/post-title',
                      attrs: {
                        isLink: true,
                        style: {
                          spacing: {
                            margin: {
                              top: '0',
                              right: '0',
                              bottom: '0',
                              left: '0',
                            },
                          },
                          layout: { selfStretch: 'fit' },
                          typography: {
                            fontStyle: 'normal',
                            fontWeight: '500',
                            lineHeight: '1.1',
                            textTransform: 'uppercase',
                            fontSize: '5.2rem',
                          },
                          elements: {
                            link: {
                              color: { text: 'var:preset|color|contrast' },
                            },
                          },
                        },
                        textColor: 'contrast',
                      },
                      innerBlocks: [],
                      innerHTML: '',
                      innerContent: [],
                    },
                  ],
                  innerHTML:
                    '\n<div class="wp-block-group" style="padding-top:16px;padding-right:16px;padding-bottom:var(--wp--preset--spacing--70);padding-left:16px"><\/div>\n',
                  innerContent: [
                    '\n<div class="wp-block-group" style="padding-top:16px;padding-right:16px;padding-bottom:var(--wp--preset--spacing--70);padding-left:16px">',
                    null,
                    '<\/div>\n',
                  ],
                },
              ],
              innerHTML: '\n\n\n\n',
              innerContent: ['\n', null, '\n\n', null, '\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-group alignfull" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-group alignfull" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0">',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/group',
          attrs: {
            style: {
              spacing: {
                padding: {
                  top: 'var:preset|spacing|30',
                  bottom: 'var:preset|spacing|30',
                  right: '16px',
                  left: '16px',
                },
                margin: { top: '0', bottom: '0' },
              },
            },
            layout: { type: 'default' },
          },
          innerBlocks: [
            {
              blockName: 'core\/query-pagination',
              attrs: {
                layout: {
                  type: 'flex',
                  flexWrap: 'nowrap',
                  justifyContent: 'left',
                },
              },
              innerBlocks: [
                {
                  blockName: 'core\/query-pagination-previous',
                  attrs: {
                    label: 'Previous',
                    style: { typography: { textTransform: 'uppercase' } },
                    fontSize: 'small',
                  },
                  innerBlocks: [],
                  innerHTML: '',
                  innerContent: [],
                },
                {
                  blockName: 'core\/query-pagination-next',
                  attrs: {
                    label: 'Next',
                    style: { typography: { textTransform: 'uppercase' } },
                    fontSize: 'small',
                  },
                  innerBlocks: [],
                  innerHTML: '',
                  innerContent: [],
                },
              ],
              innerHTML: '\n\n\n\n',
              innerContent: ['\n', null, '\n\n', null, '\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--30);padding-right:16px;padding-bottom:var(--wp--preset--spacing--30);padding-left:16px"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--30);padding-right:16px;padding-bottom:var(--wp--preset--spacing--30);padding-left:16px">',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-query alignfull">\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-query alignfull">',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Avatar:<\/p>\n',
      innerContent: ['\n<p>Avatar:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/avatar',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Title:<\/p>\n',
      innerContent: ['\n<p>Title:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-title',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Excerpt:<\/p>\n',
      innerContent: ['\n<p>Excerpt:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-excerpt',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Featured Image:<\/p>\n',
      innerContent: ['\n<p>Featured Image:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-featured-image',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Author Name:<\/p>\n',
      innerContent: ['\n<p>Author Name:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-author-name',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Comments Count:<\/p>\n',
      innerContent: ['\n<p>Comments Count:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-comments-count',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Comments Link:<\/p>\n',
      innerContent: ['\n<p>Comments Link:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-comments-link',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Date:<\/p>\n',
      innerContent: ['\n<p>Date:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-date',
      attrs: { datetime: '2026-07-08T07:30:44.542Z' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Post Date:<\/p>\n',
      innerContent: ['\n<p>Post Date:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-date',
      attrs: {
        metadata: {
          bindings: {
            datetime: { source: 'core\/post-data', args: { field: 'date' } },
          },
        },
      },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Modified Date:<\/p>\n',
      innerContent: ['\n<p>Modified Date:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-date',
      attrs: {
        metadata: {
          bindings: {
            datetime: {
              source: 'core\/post-data',
              args: { field: 'modified' },
            },
          },
        },
        className: 'wp-block-post-date__modified-date',
      },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Categories:<\/p>\n',
      innerContent: ['\n<p>Categories:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-terms',
      attrs: { term: 'category' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Tags:<\/p>\n',
      innerContent: ['\n<p>Tags:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-terms',
      attrs: { term: 'post_tag' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Previous Post:<\/p>\n',
      innerContent: ['\n<p>Previous Post:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-navigation-link',
      attrs: { type: 'previous' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Next Post:<\/p>\n',
      innerContent: ['\n<p>Next Post:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-navigation-link',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Time to Read:<\/p>\n',
      innerContent: ['\n<p>Time to Read:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-time-to-read',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Word Count:<\/p>\n',
      innerContent: ['\n<p>Word Count:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-time-to-read',
      attrs: { displayMode: 'words' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Read More (default text):<\/p>\n',
      innerContent: ['\n<p>Read More (default text):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/read-more',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Read More (custom text):<\/p>\n',
      innerContent: ['\n<p>Read More (custom text):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/read-more',
      attrs: { content: 'Check this post link' },
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Comments:<\/p>\n',
      innerContent: ['\n<p>Comments:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/comments',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/comments-title',
          attrs: [],
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
        {
          blockName: 'core\/comment-template',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/columns',
              attrs: [],
              innerBlocks: [
                {
                  blockName: 'core\/column',
                  attrs: { width: '40px' },
                  innerBlocks: [
                    {
                      blockName: 'core\/avatar',
                      attrs: {
                        size: 40,
                        style: { border: { radius: '20px' } },
                      },
                      innerBlocks: [],
                      innerHTML: '',
                      innerContent: [],
                    },
                  ],
                  innerHTML:
                    '\n<div class="wp-block-column" style="flex-basis:40px"><\/div>\n',
                  innerContent: [
                    '\n<div class="wp-block-column" style="flex-basis:40px">',
                    null,
                    '<\/div>\n',
                  ],
                },
                {
                  blockName: 'core\/column',
                  attrs: [],
                  innerBlocks: [
                    {
                      blockName: 'core\/comment-author-name',
                      attrs: { fontSize: 'small' },
                      innerBlocks: [],
                      innerHTML: '',
                      innerContent: [],
                    },
                    {
                      blockName: 'core\/group',
                      attrs: {
                        style: {
                          spacing: { margin: { top: '0px', bottom: '0px' } },
                        },
                        layout: { type: 'flex' },
                      },
                      innerBlocks: [
                        {
                          blockName: 'core\/comment-date',
                          attrs: { fontSize: 'small' },
                          innerBlocks: [],
                          innerHTML: '',
                          innerContent: [],
                        },
                        {
                          blockName: 'core\/comment-edit-link',
                          attrs: { fontSize: 'small' },
                          innerBlocks: [],
                          innerHTML: '',
                          innerContent: [],
                        },
                      ],
                      innerHTML:
                        '\n<div class="wp-block-group" style="margin-top:0px;margin-bottom:0px">\n\n<\/div>\n',
                      innerContent: [
                        '\n<div class="wp-block-group" style="margin-top:0px;margin-bottom:0px">',
                        null,
                        '\n\n',
                        null,
                        '<\/div>\n',
                      ],
                    },
                    {
                      blockName: 'core\/comment-content',
                      attrs: [],
                      innerBlocks: [],
                      innerHTML: '',
                      innerContent: [],
                    },
                    {
                      blockName: 'core\/comment-reply-link',
                      attrs: { fontSize: 'small' },
                      innerBlocks: [],
                      innerHTML: '',
                      innerContent: [],
                    },
                  ],
                  innerHTML:
                    '\n<div class="wp-block-column">\n\n\n\n\n\n<\/div>\n',
                  innerContent: [
                    '\n<div class="wp-block-column">',
                    null,
                    '\n\n',
                    null,
                    '\n\n',
                    null,
                    '\n\n',
                    null,
                    '<\/div>\n',
                  ],
                },
              ],
              innerHTML: '\n<div class="wp-block-columns">\n\n<\/div>\n',
              innerContent: [
                '\n<div class="wp-block-columns">',
                null,
                '\n\n',
                null,
                '<\/div>\n',
              ],
            },
          ],
          innerHTML: '\n\n',
          innerContent: ['\n', null, '\n'],
        },
        {
          blockName: 'core\/comments-pagination',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/comments-pagination-previous',
              attrs: [],
              innerBlocks: [],
              innerHTML: '',
              innerContent: [],
            },
            {
              blockName: 'core\/comments-pagination-numbers',
              attrs: [],
              innerBlocks: [],
              innerHTML: '',
              innerContent: [],
            },
            {
              blockName: 'core\/comments-pagination-next',
              attrs: [],
              innerBlocks: [],
              innerHTML: '',
              innerContent: [],
            },
          ],
          innerHTML: '\n\n\n\n\n\n',
          innerContent: ['\n', null, '\n\n', null, '\n\n', null, '\n'],
        },
        {
          blockName: 'core\/post-comments-form',
          attrs: [],
          innerBlocks: [],
          innerHTML: '',
          innerContent: [],
        },
      ],
      innerHTML: '\n<div class="wp-block-comments">\n\n\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-comments">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Comments Form:<\/p>\n',
      innerContent: ['\n<p>Comments Form:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-comments-form',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Author Biagraphy:<\/p>\n',
      innerContent: ['\n<p>Author Biagraphy:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/post-author-biography',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Breadcrumbs:<\/p>\n',
      innerContent: ['\n<p>Breadcrumbs:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/breadcrumbs',
      attrs: [],
      innerBlocks: [],
      innerHTML: '',
      innerContent: [],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>There is pretty much nothing worth seeing here and most of the blocks should be skipped as they are site specific and not post specific.<\/p>\n',
      innerContent: [
        '\n<p>There is pretty much nothing worth seeing here and most of the blocks should be skipped as they are site specific and not post specific.<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><\/p>\n',
      innerContent: ['\n<p><\/p>\n'],
    },
  ],
};
