/* eslint-disable no-useless-escape */
export const designOverviewResponse = {
  id: 19,
  title: 'Design overview',
  shortDescription:
    'Lets take a look at Design blocks: Accordion: Buttons: Buttons with align center: Buttons with align right: Columns (one column with 100%): a paragraph inside column and image below: Columns (two columns with 50\/50): paragraph inside left column paragraph inside right column and an image below in right column: Columns (two columns with 33\/66): left [&hellip;]',
  previewImage: false,
  date: '2026-09-14 19:09:24',
  author: {
    nickname: null,
    name: ' ',
    description: null,
    avatarUrl:
      'https:\/\/secure.gravatar.com\/avatar\/8368b6b19c1f0ef13e2e416945f18182054a70e82f74bc1a2ea160021c70f8aa?s=96&d=mm&r=g',
  },
  blocks: [
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Lets take a look at Design blocks:<\/p>\n',
      innerContent: ['\n<p>Lets take a look at Design blocks:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Accordion:<\/p>\n',
      innerContent: ['\n<p>Accordion:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/accordion',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/accordion-item',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/accordion-heading',
              attrs: [],
              innerBlocks: [],
              innerHTML:
                '\n<h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">Accordion title<\/span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+<\/span><\/button><\/h3>\n',
              innerContent: [
                '\n<h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">Accordion title<\/span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+<\/span><\/button><\/h3>\n',
              ],
            },
            {
              blockName: 'core\/accordion-panel',
              attrs: [],
              innerBlocks: [
                {
                  blockName: 'core\/paragraph',
                  attrs: [],
                  innerBlocks: [],
                  innerHTML: '\n<p>paragraph inside accordion panel<\/p>\n',
                  innerContent: [
                    '\n<p>paragraph inside accordion panel<\/p>\n',
                  ],
                },
                {
                  blockName: 'core\/paragraph',
                  attrs: [],
                  innerBlocks: [],
                  innerHTML: '\n<p>and another one<\/p>\n',
                  innerContent: ['\n<p>and another one<\/p>\n'],
                },
              ],
              innerHTML:
                '\n<div role="region" class="wp-block-accordion-panel">\n\n<\/div>\n',
              innerContent: [
                '\n<div role="region" class="wp-block-accordion-panel">',
                null,
                '\n\n',
                null,
                '<\/div>\n',
              ],
            },
          ],
          innerHTML: '\n<div class="wp-block-accordion-item">\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-accordion-item">',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/accordion-item',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/accordion-heading',
              attrs: [],
              innerBlocks: [],
              innerHTML:
                '\n<h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">Another accordion item<\/span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+<\/span><\/button><\/h3>\n',
              innerContent: [
                '\n<h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">Another accordion item<\/span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+<\/span><\/button><\/h3>\n',
              ],
            },
            {
              blockName: 'core\/accordion-panel',
              attrs: [],
              innerBlocks: [
                {
                  blockName: 'core\/paragraph',
                  attrs: [],
                  innerBlocks: [],
                  innerHTML:
                    '\n<p>and another accordion panel paragraph with an image below:<\/p>\n',
                  innerContent: [
                    '\n<p>and another accordion panel paragraph with an image below:<\/p>\n',
                  ],
                },
                {
                  blockName: 'core\/image',
                  attrs: { sizeSlug: 'large' },
                  innerBlocks: [],
                  innerHTML:
                    '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
                  innerContent: [
                    '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
                  ],
                },
              ],
              innerHTML:
                '\n<div role="region" class="wp-block-accordion-panel">\n\n<\/div>\n',
              innerContent: [
                '\n<div role="region" class="wp-block-accordion-panel">',
                null,
                '\n\n',
                null,
                '<\/div>\n',
              ],
            },
          ],
          innerHTML: '\n<div class="wp-block-accordion-item">\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-accordion-item">',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/accordion-item',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/accordion-heading',
              attrs: [],
              innerBlocks: [],
              innerHTML:
                '\n<h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">a third accordion item<\/span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+<\/span><\/button><\/h3>\n',
              innerContent: [
                '\n<h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">a third accordion item<\/span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+<\/span><\/button><\/h3>\n',
              ],
            },
            {
              blockName: 'core\/accordion-panel',
              attrs: [],
              innerBlocks: [
                {
                  blockName: 'core\/paragraph',
                  attrs: [],
                  innerBlocks: [],
                  innerHTML: '\n<p>this time with a nested list inside:<\/p>\n',
                  innerContent: [
                    '\n<p>this time with a nested list inside:<\/p>\n',
                  ],
                },
                {
                  blockName: 'core\/list',
                  attrs: [],
                  innerBlocks: [
                    {
                      blockName: 'core\/list-item',
                      attrs: [],
                      innerBlocks: [
                        {
                          blockName: 'core\/list',
                          attrs: { ordered: true },
                          innerBlocks: [
                            {
                              blockName: 'core\/list-item',
                              attrs: [],
                              innerBlocks: [],
                              innerHTML: '\n<li>with nested numbered<\/li>\n',
                              innerContent: [
                                '\n<li>with nested numbered<\/li>\n',
                              ],
                            },
                            {
                              blockName: 'core\/list-item',
                              attrs: [],
                              innerBlocks: [],
                              innerHTML: '\n<li>element 3<\/li>\n',
                              innerContent: ['\n<li>element 3<\/li>\n'],
                            },
                          ],
                          innerHTML: '\n<ol class="wp-block-list">\n\n<\/ol>\n',
                          innerContent: [
                            '\n<ol class="wp-block-list">',
                            null,
                            '\n\n',
                            null,
                            '<\/ol>\n',
                          ],
                        },
                      ],
                      innerHTML: '\n<li>a simple unorderd list<\/li>\n',
                      innerContent: [
                        '\n<li>a simple unorderd list',
                        null,
                        '<\/li>\n',
                      ],
                    },
                  ],
                  innerHTML: '\n<ul class="wp-block-list"><\/ul>\n',
                  innerContent: [
                    '\n<ul class="wp-block-list">',
                    null,
                    '<\/ul>\n',
                  ],
                },
              ],
              innerHTML:
                '\n<div role="region" class="wp-block-accordion-panel">\n\n<\/div>\n',
              innerContent: [
                '\n<div role="region" class="wp-block-accordion-panel">',
                null,
                '\n\n',
                null,
                '<\/div>\n',
              ],
            },
          ],
          innerHTML: '\n<div class="wp-block-accordion-item">\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-accordion-item">',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML:
        '\n<div role="group" class="wp-block-accordion">\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div role="group" class="wp-block-accordion">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Buttons:<\/p>\n',
      innerContent: ['\n<p>Buttons:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/buttons',
      attrs: { layout: { type: 'flex', justifyContent: 'left' } },
      innerBlocks: [
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">example button text without any link<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">example button text without any link<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https:\/\/google.com">another button with link to google<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https:\/\/google.com">another button with link to google<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with <strong><em>bold italic<\/em><\/strong> text<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with <strong><em>bold italic<\/em><\/strong> text<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with super<sup>script<\/sup><\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with super<sup>script<\/sup><\/a><\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-buttons">\n\n\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-buttons">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Buttons with align center:<\/p>\n',
      innerContent: ['\n<p>Buttons with align center:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/buttons',
      attrs: { layout: { type: 'flex', justifyContent: 'center' } },
      innerBlocks: [
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">example button text without any link<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">example button text without any link<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https:\/\/google.com">another button with link to google<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https:\/\/google.com">another button with link to google<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with <strong><em>bold italic<\/em><\/strong> text<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with <strong><em>bold italic<\/em><\/strong> text<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with super<sup>script<\/sup><\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with super<sup>script<\/sup><\/a><\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-buttons">\n\n\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-buttons">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Buttons with align right:<\/p>\n',
      innerContent: ['\n<p>Buttons with align right:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/buttons',
      attrs: { layout: { type: 'flex', justifyContent: 'right' } },
      innerBlocks: [
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">example button text without any link<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">example button text without any link<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https:\/\/google.com">another button with link to google<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https:\/\/google.com">another button with link to google<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with <strong><em>bold italic<\/em><\/strong> text<\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with <strong><em>bold italic<\/em><\/strong> text<\/a><\/div>\n',
          ],
        },
        {
          blockName: 'core\/button',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with super<sup>script<\/sup><\/a><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">a button with super<sup>script<\/sup><\/a><\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-buttons">\n\n\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-buttons">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Columns (one column with 100%):<\/p>\n',
      innerContent: ['\n<p>Columns (one column with 100%):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/columns',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/column',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>a paragraph inside column<\/p>\n',
              innerContent: ['\n<p>a paragraph inside column<\/p>\n'],
            },
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>and image below:<\/p>\n',
              innerContent: ['\n<p>and image below:<\/p>\n'],
            },
            {
              blockName: 'core\/image',
              attrs: { sizeSlug: 'large' },
              innerBlocks: [],
              innerHTML:
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              innerContent: [
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              ],
            },
          ],
          innerHTML: '\n<div class="wp-block-column">\n\n\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column">',
            null,
            '\n\n',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-columns"><\/div>\n',
      innerContent: ['\n<div class="wp-block-columns">', null, '<\/div>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Columns (two columns with 50\/50):<\/p>\n',
      innerContent: ['\n<p>Columns (two columns with 50\/50):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/columns',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/column',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>paragraph inside left column<\/p>\n',
              innerContent: ['\n<p>paragraph inside left column<\/p>\n'],
            },
          ],
          innerHTML: '\n<div class="wp-block-column"><\/div>\n',
          innerContent: ['\n<div class="wp-block-column">', null, '<\/div>\n'],
        },
        {
          blockName: 'core\/column',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>paragraph inside right column<\/p>\n',
              innerContent: ['\n<p>paragraph inside right column<\/p>\n'],
            },
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>and an image below in right column:<\/p>\n',
              innerContent: ['\n<p>and an image below in right column:<\/p>\n'],
            },
            {
              blockName: 'core\/image',
              attrs: { sizeSlug: 'large' },
              innerBlocks: [],
              innerHTML:
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              innerContent: [
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              ],
            },
          ],
          innerHTML: '\n<div class="wp-block-column">\n\n\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column">',
            null,
            '\n\n',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-columns">\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-columns">',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br>Columns (two columns with 33\/66):<\/p>\n',
      innerContent: ['\n<p><br>Columns (two columns with 33\/66):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/columns',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/column',
          attrs: { width: '33.33%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML:
                '\n<p>left smaller column text with an image below:<\/p>\n',
              innerContent: [
                '\n<p>left smaller column text with an image below:<\/p>\n',
              ],
            },
            {
              blockName: 'core\/image',
              attrs: { sizeSlug: 'large' },
              innerBlocks: [],
              innerHTML:
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              innerContent: [
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              ],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:33.33%">\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:33.33%">',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/column',
          attrs: { width: '66.66%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>right wider column text paragraph<\/p>\n',
              innerContent: ['\n<p>right wider column text paragraph<\/p>\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:66.66%"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:66.66%">',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-columns">\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-columns">',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Columns (two columns with 66\/33):<\/p>\n',
      innerContent: ['\n<p>Columns (two columns with 66\/33):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/columns',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/column',
          attrs: { width: '66.66%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML:
                '\n<p>left wider column text with an image below:<\/p>\n',
              innerContent: [
                '\n<p>left wider column text with an image below:<\/p>\n',
              ],
            },
            {
              blockName: 'core\/image',
              attrs: { sizeSlug: 'large' },
              innerBlocks: [],
              innerHTML:
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              innerContent: [
                '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
              ],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:66.66%">\n\n<\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:66.66%">',
            null,
            '\n\n',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/column',
          attrs: { width: '33.33%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>right smaller column text paragraph<\/p>\n',
              innerContent: ['\n<p>right smaller column text paragraph<\/p>\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:33.33%"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:33.33%">',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-columns">\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-columns">',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Columns (three columns with 33\/33\/33):<\/p>\n',
      innerContent: ['\n<p>Columns (three columns with 33\/33\/33):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/columns',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/column',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>left column paragraph<\/p>\n',
              innerContent: ['\n<p>left column paragraph<\/p>\n'],
            },
          ],
          innerHTML: '\n<div class="wp-block-column"><\/div>\n',
          innerContent: ['\n<div class="wp-block-column">', null, '<\/div>\n'],
        },
        {
          blockName: 'core\/column',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>center column paragraph<\/p>\n',
              innerContent: ['\n<p>center column paragraph<\/p>\n'],
            },
          ],
          innerHTML: '\n<div class="wp-block-column"><\/div>\n',
          innerContent: ['\n<div class="wp-block-column">', null, '<\/div>\n'],
        },
        {
          blockName: 'core\/column',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>right column paragraph<\/p>\n',
              innerContent: ['\n<p>right column paragraph<\/p>\n'],
            },
          ],
          innerHTML: '\n<div class="wp-block-column"><\/div>\n',
          innerContent: ['\n<div class="wp-block-column">', null, '<\/div>\n'],
        },
      ],
      innerHTML: '\n<div class="wp-block-columns">\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-columns">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Columns (three columns with 25\/50\/25):<\/p>\n',
      innerContent: ['\n<p>Columns (three columns with 25\/50\/25):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/columns',
      attrs: [],
      innerBlocks: [
        {
          blockName: 'core\/column',
          attrs: { width: '25%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>left small column paragraph<\/p>\n',
              innerContent: ['\n<p>left small column paragraph<\/p>\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:25%"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:25%">',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/column',
          attrs: { width: '50%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>center wider column paragraph<\/p>\n',
              innerContent: ['\n<p>center wider column paragraph<\/p>\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:50%"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:50%">',
            null,
            '<\/div>\n',
          ],
        },
        {
          blockName: 'core\/column',
          attrs: { width: '25%' },
          innerBlocks: [
            {
              blockName: 'core\/paragraph',
              attrs: [],
              innerBlocks: [],
              innerHTML: '\n<p>right small column paragraph<\/p>\n',
              innerContent: ['\n<p>right small column paragraph<\/p>\n'],
            },
          ],
          innerHTML:
            '\n<div class="wp-block-column" style="flex-basis:25%"><\/div>\n',
          innerContent: [
            '\n<div class="wp-block-column" style="flex-basis:25%">',
            null,
            '<\/div>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-columns">\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-columns">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Group (single container):<\/p>\n',
      innerContent: ['\n<p>Group (single container):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/group',
      attrs: { layout: { type: 'constrained' } },
      innerBlocks: [
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<p>a simple container group with nothing special to it.<\/p>\n',
          innerContent: [
            '\n<p>a simple container group with nothing special to it.<\/p>\n',
          ],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<p>lets add another paragraph and an image below:<\/p>\n',
          innerContent: [
            '\n<p>lets add another paragraph and an image below:<\/p>\n',
          ],
        },
        {
          blockName: 'core\/image',
          attrs: { sizeSlug: 'large' },
          innerBlocks: [],
          innerHTML:
            '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
          innerContent: [
            '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
          ],
        },
      ],
      innerHTML: '\n<div class="wp-block-group">\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-group">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>Group\/Row ("two" columns [actually three, cause we can add as many as we want], that gets automatically converted into row block):<\/p>\n',
      innerContent: [
        '\n<p>Group\/Row ("two" columns [actually three, cause we can add as many as we want], that gets automatically converted into row block):<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/group',
      attrs: { layout: { type: 'flex', flexWrap: 'nowrap' } },
      innerBlocks: [
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>left container side paragraph<\/p>\n',
          innerContent: ['\n<p>left container side paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>center container paragraph<\/p>\n',
          innerContent: ['\n<p>center container paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>right container side paragraph<\/p>\n',
          innerContent: ['\n<p>right container side paragraph<\/p>\n'],
        },
      ],
      innerHTML: '\n<div class="wp-block-group">\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-group">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>Group\/Column ("two" rows [actually three, cause we can add as many as we want], that gets automatically converted into stack block):<\/p>\n',
      innerContent: [
        '\n<p>Group\/Column ("two" rows [actually three, cause we can add as many as we want], that gets automatically converted into stack block):<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/group',
      attrs: { layout: { type: 'flex', orientation: 'vertical' } },
      innerBlocks: [
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>a first row paragraph<\/p>\n',
          innerContent: ['\n<p>a first row paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>second row paragraph<\/p>\n',
          innerContent: ['\n<p>second row paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>and a third row paragraph<\/p>\n',
          innerContent: ['\n<p>and a third row paragraph<\/p>\n'],
        },
      ],
      innerHTML: '\n<div class="wp-block-group">\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-group">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p>Group\/Grid (combination of two previous variants):<\/p>\n',
      innerContent: [
        '\n<p>Group\/Grid (combination of two previous variants):<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/group',
      attrs: { layout: { type: 'grid' } },
      innerBlocks: [
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>top-left paragraph<\/p>\n',
          innerContent: ['\n<p>top-left paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>top-center paragraph<\/p>\n',
          innerContent: ['\n<p>top-center paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>top-right paragraph<\/p>\n',
          innerContent: ['\n<p>top-right paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>center-left paragraph<\/p>\n',
          innerContent: ['\n<p>center-left paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>center-center<\/p>\n',
          innerContent: ['\n<p>center-center<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>center-right paragraph<\/p>\n',
          innerContent: ['\n<p>center-right paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>bottom-left paragraph<\/p>\n',
          innerContent: ['\n<p>bottom-left paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>bottom-center paragraph<\/p>\n',
          innerContent: ['\n<p>bottom-center paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML: '\n<p>bottom-right paragraph<\/p>\n',
          innerContent: ['\n<p>bottom-right paragraph<\/p>\n'],
        },
        {
          blockName: 'core\/paragraph',
          attrs: [],
          innerBlocks: [],
          innerHTML:
            '\n<p>and a 4th row with image in second column and nested list in 3rd<\/p>\n',
          innerContent: [
            '\n<p>and a 4th row with image in second column and nested list in 3rd<\/p>\n',
          ],
        },
        {
          blockName: 'core\/image',
          attrs: { sizeSlug: 'large' },
          innerBlocks: [],
          innerHTML:
            '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
          innerContent: [
            '\n<figure class="wp-block-image size-large"><img src="https:\/\/placehold.net\/400x400.png" alt=""\/><\/figure>\n',
          ],
        },
        {
          blockName: 'core\/list',
          attrs: [],
          innerBlocks: [
            {
              blockName: 'core\/list-item',
              attrs: [],
              innerBlocks: [
                {
                  blockName: 'core\/list',
                  attrs: { ordered: true },
                  innerBlocks: [
                    {
                      blockName: 'core\/list-item',
                      attrs: [],
                      innerBlocks: [],
                      innerHTML: '\n<li>nested ordered list<\/li>\n',
                      innerContent: ['\n<li>nested ordered list<\/li>\n'],
                    },
                    {
                      blockName: 'core\/list-item',
                      attrs: [],
                      innerBlocks: [],
                      innerHTML: '\n<li>element 3<\/li>\n',
                      innerContent: ['\n<li>element 3<\/li>\n'],
                    },
                  ],
                  innerHTML: '\n<ol class="wp-block-list">\n\n<\/ol>\n',
                  innerContent: [
                    '\n<ol class="wp-block-list">',
                    null,
                    '\n\n',
                    null,
                    '<\/ol>\n',
                  ],
                },
              ],
              innerHTML: '\n<li>unordered list<\/li>\n',
              innerContent: ['\n<li>unordered list', null, '<\/li>\n'],
            },
          ],
          innerHTML: '\n<ul class="wp-block-list"><\/ul>\n',
          innerContent: ['\n<ul class="wp-block-list">', null, '<\/ul>\n'],
        },
      ],
      innerHTML:
        '\n<div class="wp-block-group">\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<\/div>\n',
      innerContent: [
        '\n<div class="wp-block-group">',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '\n\n',
        null,
        '<\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>More (with custom text):<\/p>\n',
      innerContent: ['\n<p>More (with custom text):<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/more',
      attrs: { customText: 'custom read more text' },
      innerBlocks: [],
      innerHTML: '\n<!--more custom read more text-->\n',
      innerContent: ['\n<!--more custom read more text-->\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Page break:<\/p>\n',
      innerContent: ['\n<p>Page break:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/nextpage',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<!--nextpage-->\n',
      innerContent: ['\n<!--nextpage-->\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>some content on the second page<\/p>\n',
      innerContent: ['\n<p>some content on the second page<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>another page break:<\/p>\n',
      innerContent: ['\n<p>another page break:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/nextpage',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<!--nextpage-->\n',
      innerContent: ['\n<!--nextpage-->\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>sample paragraph on the third page<\/p>\n',
      innerContent: ['\n<p>sample paragraph on the third page<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Separator:<\/p>\n',
      innerContent: ['\n<p>Separator:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>text before<\/p>\n',
      innerContent: ['\n<p>text before<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/separator',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<hr class="wp-block-separator has-alpha-channel-opacity"\/>\n',
      innerContent: [
        '\n<hr class="wp-block-separator has-alpha-channel-opacity"\/>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>text after<\/p>\n',
      innerContent: ['\n<p>text after<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><br><\/p>\n',
      innerContent: ['\n<p><br><\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>Spacer:<\/p>\n',
      innerContent: ['\n<p>Spacer:<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>text before<\/p>\n',
      innerContent: ['\n<p>text before<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/spacer',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<div style="height:100px" aria-hidden="true" class="wp-block-spacer"><\/div>\n',
      innerContent: [
        '\n<div style="height:100px" aria-hidden="true" class="wp-block-spacer"><\/div>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p>text after<\/p>\n',
      innerContent: ['\n<p>text after<\/p>\n'],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML:
        '\n<p><br>That should pretty much sum up Design blocks overview.<\/p>\n',
      innerContent: [
        '\n<p><br>That should pretty much sum up Design blocks overview.<\/p>\n',
      ],
    },
    {
      blockName: null,
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n\n',
      innerContent: ['\n\n'],
    },
    {
      blockName: 'core\/paragraph',
      attrs: [],
      innerBlocks: [],
      innerHTML: '\n<p><\/p>\n',
      innerContent: ['\n<p><\/p>\n'],
    },
  ],
};
